### ISSUE TITLE
Saving to a file

### ISSUE THREAD

**Issue by Symbolics** [RodrigoZepeda/d3lisp#3]
Is it possible to save the D3 output to a HTML file so that it could be loaded by the browser from disk? Hutchentoot is a heavyweight dependency for what seems like simply taking data from disk to the browser anyway (but via http://). Is it possible to do this with file:// ?

**Comment by RodrigoZepeda** [comment]
I have removed the Hutchentoot dependency in order to save directly to an html file. You can now run the following example (assuming d3lisp is in your desktop):

```
;;Set directory to functions
(setf *default-pathname-defaults* (truename "~/Desktop/d3lisp/src"))

;;Load functions
(load "setup.lisp")

;;Create plot
(let* (
        (x (list 0 0.5 1 1.5 2 2.5 3 3.5 4 4.5 5))
        (y (mapcar #'exp x))
      )
      (createplot x y :title "Exponential"  :squareplot T  
                      :title-fontsize 100 
                      :margin (list 10 10 10 10)
                      :padding (list 150 30 60 60) 
                      :xlab "x" :ylab "exp(x)" 
                      :interpolation "MonotoneX"
                      :filename "MyFirstPlot")
)
```

Which saves to `MyFirstPlot.html`. Really appreciate your input.
