### ISSUE TITLE
Feature request: Save svg from create-plot

### ISSUE THREAD

**Issue by Symbolics** [RodrigoZepeda/d3lisp#8]
The HTML has an option to save the plot on the generate webpage. It would be useful to be able to specify saving an svg directly from the create-plot function so it does not have to be manually saved from the browser.

**Comment by RodrigoZepeda** [comment]
To do this we still need to open and close the browser (can be via LISP) as the Javascript code needs to be run somewhere.

**Comment by Symbolics** [comment]
It looks like there are a few options, like node.js, but in either case that fundamental problem remains. Perhaps this is not worth the trouble at the moment.
