### ISSUE TITLE
Proposal: setf instead of setq

### ISSUE THREAD

**Issue by Symbolics** [RodrigoZepeda/d3lisp#9]
Generally `setq` is only seen these days in emacs and `setf` is the generally accepted 'best practice' in setting variables in common lisp.

References:
[Gigamonkeys chapter on variables](http://www.gigamonkeys.com/book/variables.html)
[Reddit discussion on clisp subreddit](https://www.reddit.com/r/lisp/comments/74w9nl/setf_clisp_confused_about_it/)
[Stackoverflow discussion on difference in the set* operators](https://stackoverflow.com/questions/869529/difference-between-set-setq-and-setf-in-common-lisp)

This proposal would replace all occurrences of `setq` with `setf`

**Comment by RodrigoZepeda** [comment]
I now use let in most of the examples (setf is not well defined for new variables across different implementations). Setq is now gone from the code.
